name: Linting 

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run lint
